### ISSUE TITLE
docker on raspberry pi, errors

### ISSUE THREAD

**Issue by halfagascan** [EdoFede/123Solar-meterN-Docker#2]
pi@raspberrypi:~ $ docker logs 123Solar
- runit: $Id: 25da3b86f7bed4038b8a039d2f8e8c9bbcf0822b $: booting.
- runit: warning: unable to open /dev/console: file does not exist
- runit: enter stage: /etc/runit/1
Stage 1 scripts started
- runit: leave stage: /etc/runit/1
- runit: enter stage: /etc/runit/2
Apr 25 19:13:05 3f4b3ac806d2 syslog-ng[21]: syslog-ng starting up; version='3.19.1'
Apr 25 17:13:06 3f4b3ac806d2 runit: Starting PHP-FPM
Apr 25 17:13:07 3f4b3ac806d2 runit: Starting nginx
Apr 25 17:13:10 3f4b3ac806d2 postScripts-handler: Starting postScripts (/etc/runit/2.d/*)
Apr 25 17:13:10 3f4b3ac806d2 2.d Dummy script: Stage 2 scripts started (after services)
Apr 25 17:13:10 3f4b3ac806d2 2.d start_polling: Start 123Solar and meterN polling via bootstrap call
Apr 25 19:13:12 3f4b3ac806d2 3f4b3ac806d2 nginx: 2019/04/25 19:13:12 [error] 41#41: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  include(../config/config_main.php): failed to open stream: No such file or directory in /var/www/metern/scripts/bootmn.php on line 7
PHP message: PHP Warning:  include(): Failed opening '../config/config_main.php' for inclusion (include_path='.:/usr/share/php7') in /var/www/metern/scripts/bootmn.php on line 7
PHP message: PHP Notice:  Undefined variable: DTZ in /var/www/metern/scripts/bootmn.php on line 8
PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /var/www/metern/scripts/bootmn.php on line 8
PHP message: PHP Notice:  Undefined variable: DATEFORMAT in /var/www/metern/scripts/bootmn.php on line 11
PHP message: PHP Notice:  Undefined variable: DEBUG in /var/www/metern/scripts/bootmn.php on line 19" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /metern/scripts/bootmn.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "localhost"

**Comment by EdoFede** [comment]
Hi,
you get these error on first launch because 123Solar and meterN are not configured.
The file "config/config_main.php" is created during the first setup in the admin section.

There are only errors related to the first launch and does not prevents the system from working.

As an enhancemente I could modify the bootstrap (that launches the meters/sensors polling) call to check the existance of config files.. 

Thanks for reporting.

**Comment by EdoFede** [comment]
No sorry, there is also a bug in the update script, that does not copy config files on the first run.

I'll fix it soon.

Thanks

**Comment by EdoFede** [comment]
Fixed in latest release (v3.2)
