### ISSUE TITLE
update123solarAndMetern.sh need updt 

### ISSUE THREAD

**Issue by jeanmarc77** [EdoFede/123Solar-meterN-Docker#5]
Hi mate,
I can't pull requests on your git. You shall need to update your install script.
I have moved here too https://github.com/jeanmarc77/123solar and https://github.com/jeanmarc77/meterN
Cheers :)

**Comment by EdoFede** [comment]
Hi Jean-Marc!

Thanks for your notification.
I'm a lot busy with work in this period, but I'll update the install/update script soon!

Thank you! :)

**Comment by manny73** [comment]
Hi EdoFede, 
in the meanwhile that you prepare next release, can block auto update procedure?
The update script run and log error every 5 second! 
Great jobs!

Thanks.

**Comment by EdoFede** [comment]
Apologize for such a late reply.

I've updated all the base-image (Alpine version, PHP version, etc...) and rewrote the update script, now pointing to jeanmarc github repository.
I had a bit of trouble with Travis integration and very little free time, so it took some time.

I'm building the new version that I plan to release today.
I'll update you shortly

**Comment by EdoFede** [comment]
[New release (v4.0) published](https://github.com/EdoFede/123Solar-meterN-Docker/releases/tag/v4.0)!
Tested on my system without any issues.
